<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php $theme = 'AdminLTE'; echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/admin-style.css')
            //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/jquery.fancybox.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-switch.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-datetimepicker.min.css')
            ->prependStylesheet($this->basePath() . '/css/morris/morris.css')
            ->prependStylesheet($this->basePath() . '/css/datatables/dataTables.bootstrap.css')
            ->prependStylesheet($this->basePath() . '/css/iCheck/all.css')
            ->prependStylesheet($this->basePath() . '/css/datepicker/datepicker3.css')
            ->prependStylesheet($this->basePath() . '/themes/' . $theme . '/css/style.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="skin-blue">
        <!-- header logo: style can be found in header.less -->
        <header class="header">
            <a href="/" class="logo"></a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="glyphicon glyphicon-user"></i>
                                <span><?php echo $escaper->escapeHtml($identity['name'] . ' ' . $identity['surname']); ?><i class="caret"></i></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header bg-light-blue">
                                    <img src="../../img/avatar3.png" class="img-circle" alt="User Image" />
                                    <p>
                                        <?php echo $escaper->escapeHtml($identity['name'] . ' ' . $identity['surname']); ?> - <?php echo $escaper->escapeHtml($identity['user_group_name']); ?>
                                        <small><?php echo $this->translate('Last Updated on: ');?><?php echo $identity['modified']; ?></small>
                                    </p>
                                </li>
                                <li class="user-footer">
                                    <div class="pull-right">
                                        <a href="<?php echo $this->url('administration/logout'); ?>" class="btn btn-default btn-flat"><?php echo $this->translate('Sign out');?></a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu">
                        <li>
                            <a href="../../index.html">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                            </a>
                        </li>
                        <li class="treeview active">
                            <a href="#">
                                <i class="fa fa-folder"></i> <span>Examples</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="invoice.html"><i class="fa fa-angle-double-right"></i> Invoice</a></li>
                                <li><a href="login.html"><i class="fa fa-angle-double-right"></i> Login</a></li>
                                <li><a href="register.html"><i class="fa fa-angle-double-right"></i> Register</a></li>
                                <li><a href="lockscreen.html"><i class="fa fa-angle-double-right"></i> Lockscreen</a></li>
                                <li><a href="404.html"><i class="fa fa-angle-double-right"></i> 404 Error</a></li>
                                <li><a href="500.html"><i class="fa fa-angle-double-right"></i> 500 Error</a></li>
                                <li class="active"><a href="blank.html"><i class="fa fa-angle-double-right"></i> Blank Page</a></li>
                            </ul>
                        </li>
                    </ul>
                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">
                <?php echo $this->content; ?>
            </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->

    <?php
        echo $this->inlineScript()
            ->offsetSetFile(1, $this->basePath() . '/js/jquery.min.js')
            ->offsetSetFile(2, $this->basePath() . '/js/plugins.js')
            ->offsetSetFile(3, $this->basePath() . '/js/tinymce/tinymce.min.js')
            ->offsetSetFile(4, $this->basePath() . '/js/datatables/jquery.dataTables.js')
            ->offsetSetFile(5, $this->basePath() . '/js/datatables/dataTables.bootstrap.js')
            ->offsetSetFile(6, $this->basePath() . '/themes/' . $theme . '/js/app.js')
            ->offsetSetFile(7, $this->basePath() . '/js/admin.js')
    ?>
    </body>
</html>
