<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php $theme = 'AdminLTE'; echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/admin-style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/themes/' . $theme . '/css/style.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="bg-black">
        <div class="wrapper">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
        <?php
        echo $this->inlineScript()
            ->offsetSetFile(1, $this->basePath() . '/js/jquery.min.js')
            ->offsetSetFile(2, $this->basePath() . '/js/plugins.js')
            ->offsetSetFile(3, $this->basePath() . '/js/iCheck/icheck.min.js')
            ->offsetSetFile(4, $this->basePath() . '/themes/' . $theme . '/js/login.js')
        ?>
    </body>
</html>
