<?php if (count($errors)) : ?>
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <b><?php echo $this->translate('Errors occured while submiting this form'); ?></b>
        <ul>
            <?php foreach ($errors as $field => $messages) : ?>
                <?php foreach ($messages as $message) : ?>
                    <li><?php echo $this->translate($field) . ': ' . $message; ?></li>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>