<?php if ($field->getLabel() != ''): ?>
<div class="form-group <?php echo ($this->formElementErrors($field) != '') ? 'has-error' : ''; ?>">
    <label><?php echo ($field->getLabel() != '') ? $this->translate($field->getLabel()) : ''; ?></label>
    <div class="text-red"><?php echo  $this->formElementErrors($field, array('class' => "input_error")) ?></div>
    <?php if (array_key_exists('data-type', $field->getAttributes())) : ?>
        <?php $attributesArray = $field->getAttributes(); ?>
        <div class="input-group">
            <?php echo $this->formElement($field); ?>
            <span class="input-group-btn">
                <?php if( $field->getValue() != '' && preg_match('~(jpg|jpeg|png|gif)~i', $field->getValue())): ?>
                    <a href="<?php echo $field->getValue() ?>" class="btn btn-default image-preview" type="button">
                        <span class="glyphicon glyphicon-picture"></span>
                    </a>
                <?php endif; ?>
                <?php if ($attributesArray['data-type'] == 'date' ) : ?>
                    <a href="" class="btn btn-default datetimePickerClear" type="button">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                    <a href="" class="btn btn-default datetimePickerTrigger" type="button">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </a>
                <?php else: ?>
                    <a href="/filemanager/dialog.php?field_id=<?php echo $attributesArray['id'] ?>&type=<?php echo ($attributesArray['data-type'] == 'image')? '1':'2' ; ?>" class="btn btn-default iframe-btn " type="button"><?php echo $this->translate('Select'); ?></a>
                <?php endif;?>
            </span>
        </div>
    <?php else: ?>
        <?php echo $this->formElement($field); ?>
    <?php endif; ?>
</div>
<?php else: ?>
    <?php echo $this->formElement($field); ?>
<?php endif; ?>