<section class="content-header">
    <h1>
        <?php echo $this->translate('Model:'); ?> <?php echo $this->escapeHtml($this->translate($modelName)); ?>
        <small>Errors Detected</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Examples</a></li>
        <li class="active">Blank page</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <?php foreach ($errors as $error) : ?>
        <div class="callout callout-danger">
            <h4><?php echo $this->translate('Critical issue!'); ?></h4>
            <p><?php echo $this->escapeHtml($this->translate($error)) ?></p>
        </div>
    <?php endforeach; ?>
</section>