<section class="content-header">
    <h1>
        <?php echo $this->translate($model); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('administration'); ?>"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="<?php echo $this->url('administration/model', array('action' => 'index', 'model' => $model)); ?>"><?php echo $this->translate($model); ?></a></li>
        <?php foreach ($breadCrumbs as $crumb) : ?>
            <li><a href="<?php echo $this->url('administration/model', array('action' => 'index', 'model' => $model, 'parent' => $crumb['id'])); ?>"><?php echo $this->escapeHtml($crumb['text']); ?></a></li>
        <?php endforeach; ?>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="box">
        <div class="box-body table-responsive">
            <?php $multipleDeleteForm->prepare(); ?>
            <?php echo $this->form()->openTag($multipleDeleteForm); ?>
            <table class="table table-bordered table-striped datatable">
                <thead>
                    <tr>
                        <th width="20" class="text-center">#</th>
                    <?php foreach ($listingFields as $field => $definition) : ?>
                        <th><?php echo $this->translate($field); ?>&nbsp;&nbsp;&nbsp;</th>
                    <?php endforeach; ?>
                        <th width="<?php echo ($treeView) ? '70' : '50'; ?>">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($listing as $item) : ?>
                    <tr>
                        <td class="text-center"><input type="checkbox" name="multipleDeleteCheck[]" value="<?php echo $item->id ?>"/></td>
                    <?php $fieldCount = 0; ?>
                    <?php foreach ($listingFields as $field => $definition) : ?>
                        <?php if ($definition == 'boolean' && $permissionHelper->isAllowed($userGroup, null, 'edit')) : ?>
                            <td width="30" class="text-center"><input type="checkbox" class="simple bootstrapSwitchIndex" data-url="<?php echo $this->url('administration/model', array('action' => 'edit-single-boolean-field', 'model' => $model, 'item' => $this->escapeHtml($item->id))); ?>" data-field="<?php echo $this->escapeHtmlAttr($field) ?>" name="<?php echo $field ?>[<?php echo $item->id ?>]" <?php echo ($item->{$field}) ? 'checked' : ''; ?>></td>
                        <?php elseif ($definition == 'boolean' && !$permissionHelper->isAllowed($userGroup, null, 'edit')) : ?>
                            <td width="30" class="text-center"><span class="label label-<?php echo ($item->{$field})? 'success' : 'danger' ?>"><?php echo $this->translate( ($item->{$field}) ? 'True' : 'False'); ?></span></td>
                        <?php else: ?>
                            <td><?php echo $item->{$field}; ?></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                        <td class="text-center">
                            <div class="btn-group hidden-xs">
                                <?php if ($permissionHelper->isAllowed($userGroup, null, 'edit')) : ?>
                                <a href="<?php echo $this->url('administration/model', array('action' => 'edit', 'model' => $model, 'item' => $this->escapeHtml($item->id) )); ?>" type="button" class="btn btn-xs btn-info">
                                    <span class="glyphicon  glyphicon-pencil"></span>
                                </a>
                                <?php endif; ?>
                                <?php if ($treeView) : ?>
                                    <a href="<?php echo $this->url('administration/model', array('action' => 'index', 'model' => $model, 'parent' => $this->escapeHtml($item->id) )); ?>" type="button" class="btn btn-xs btn-primary">
                                        <span class="glyphicon glyphicon-folder-open"></span>
                                    </a>
                                <?php endif; ?>
                                <?php if ($permissionHelper->isAllowed($userGroup, null, 'delete')) : ?>
                                <a href="<?php echo $this->url('administration/model', array('action' => 'delete', 'model' => $model, 'item' => $this->escapeHtml($item->id) )); ?>" type="button" class="btn btn-xs btn-warning">
                                    <span class="glyphicon  glyphicon-trash"></span>
                                </a>
                                <?php endif; ?>
                            </div>
                            <div class="btn-group btn-group-xs visible-xs-block">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    <span class="glyphicon glyphicon-cog"></span>&nbsp;
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                    <?php if ($permissionHelper->isAllowed($userGroup, null, 'edit')) : ?>
                                        <li>
                                            <a href="<?php echo $this->url('administration/model', array('action' => 'edit', 'model' => $model, 'item' => $this->escapeHtml($item->id) )); ?>">
                                                <span class="glyphicon  glyphicon-pencil"></span>
                                                <?php echo $this->translate('Edit'); ?>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($treeView) : ?>
                                        <li>
                                            <a href="<?php echo $this->url('administration/model', array('action' => 'index', 'model' => $model, 'parent' => $this->escapeHtml($item->id) )); ?>">
                                                <span class="glyphicon  glyphicon-folder-open"></span>
                                                <?php echo $this->translate('Contents'); ?>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($permissionHelper->isAllowed($userGroup, null, 'delete')) : ?>
                                        <li>
                                            <a href="<?php echo $this->url('administration/model', array('action' => 'delete', 'model' => $model, 'item' => $this->escapeHtml($item->id) )); ?>">
                                                <span class="glyphicon  glyphicon-trash"></span>
                                                <?php echo $this->translate('Delete'); ?>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div class="btn-group">
                <?php if ($permissionHelper->isAllowed($userGroup, null, 'add')) : ?>
                <a href="<?php echo $this->url('administration/model', array('action' => 'add', 'model' => $model)); ?>" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    <?php echo $this->translate('Add New'); ?>
                </a>
                <?php endif; ?>
                <?php if ($permissionHelper->isAllowed($userGroup, null, 'delete')) : ?>
                <button type="submit" class="btn btn-warning">
                    <span class="glyphicon glyphicon-trash"></span>
                    <?php echo $this->translate('Delete Selected'); ?>
                </button>
                <?php endif; ?>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section>